services:
  app:
    image: nutantek/vlts-client-server:v2
    build: .
    container_name: vlts-client-server
    restart: always
    ports:
      - "3005:3005"
    dns:    
      - 8.8.8.8
      - 1.1.1.1 
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      TCP_PORT: 3007